### Create user
# @name user
POST http://localhost:8080/user
Content-Type: application/json

{
    "email": "dummy@dummy.com"
}

### Update user
PATCH http://localhost:8080/user
Content-Type: application/json

{
    "id": "{{user.response.body.id}}",
    "email": "dummy2@dummy.com"
}

### Read users
GET http://localhost:8080/user